name: Update README on Specific Dates

on:
  schedule:
    - cron: '0 0 25 12 *'  # Run at midnight (0:00) on December 25th
    - cron: '0 0 24 11 *'  # Run at midnight (0:00) on November 24th
    - cron: '0 0 3 10 *'   # Run at midnight (0:00) on October 3rd

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run update script
        run: node update-readme.js

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README [skip ci]"
          git push
